name: docker-euler
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.REPTOKEN }}

      - name: Build Docker image
        run: |
          docker build -t asso .

      - name: Run Docker container and save output
        run: |
          docker run asso > answer.txt

      - name: Add and Commit answer.txt
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "Arnolec"
          git add answer.txt
          git commit -m "Update answer.txt with Docker output"

      - name: Push changes to the variation branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPTOKEN }}
          branch: variation # Cible la branche variation
          force: true
