name: docker-euler
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t euler
      - name: Run Docker container
        run: |
          docker run -d --name euler
